CREATE TABLE keepbox_photos (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    caption TEXT NOT NULL,
    summary TEXT,
    file_location TEXT NOT NULL,
    date_uploaded TIMESTAMP DEFAULT now() NOT NULL,
    date_created TEXT,
    age TEXT,
    user_id INTEGER REFERENCES keepbox_users(id),
    album_id INTEGER REFERENCES keepbox_albums(id)
);